### NYU CDS

### Fall 2021

### Introduction to Data Science

### Project 2

### student netid: yy2197

### deadline: Dec 06, 2021, 11:59pm

---
# Data analysis Project 2
### Correlation and Regression of Movie Ratings Data
---

### Dataset description

This dataset features ratings data of 400 movies from 1097 research participants. 

* 1st row: Headers (Movie titles/questions) – note that the indexing in this list is from 1
* Row 2-1098: Responses from individual participants
* Columns 1-400: These columns contain the ratings for the 400 movies (0 to 4, and missing)
* Columns 401-421: These columns contain self-assessments on sensation seeking behaviors (1-5)
* Columns 422-464: These columns contain responses to personality questions (1-5)
* Columns 465-474: These columns contain self-reported movie experience ratings (1-5)
* Column 475: Gender identity (1 = female, 2 = male, 3 = self-described)
* Column 476: Only child (1 = yes, 0 = no, -1 = no response)
* Column 477: Movies are best enjoyed alone (1 = yes, 0 = no, -1 = no response)

Note that we did most of the data munging for you already (e.g. Python interprets commas in a csv file as separators, so we removed all commas from movie titles), but you still need to handle missing data.




### Q1:


**Note:** For all missing values in the data, use the average of the corresponding column so to fill in the missing data. 



In this problem, under **the most correlated**, we consider the largest correlation in the absolute value.


1.1. For every user in the given data, find its most correlated user. 

1.2. What is the pair of the most correlated users in the data? 

1.3. What is the value of this highest correlation?

1.4. For users 0, 1, 2, \dots, 9, print their most correlated users. 

In [1]:
import numpy as np
import pandas as pd
data = pd.read_csv("movieReplicationSet.csv")
print(data.iloc[896])
print(data.iloc[831])

for index,value in enumerate(data.columns):
    meanVal = np.mean(data[value])
    data[value] = data[value].fillna(meanVal)
buf = data.iloc[:,0:474]

corr = buf.T
corr = corr.reset_index(drop=True)
res = corr.corr()

print(res)

res = res.to_numpy()
res = res - np.identity(1097)

c:\users\tonyyyyy\pycharmprojects\pythonproject\venv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\users\tonyyyyy\pycharmprojects\pythonproject\venv\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
c:\users\tonyyyyy\pycharmprojects\pythonproject\venv\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


The Life of David Gale (2003)                                              NaN
Wing Commander (1999)                                                      NaN
Django Unchained (2012)                                                    NaN
Alien (1979)                                                               NaN
Indiana Jones and the Last Crusade (1989)                                  NaN
                                                                          ... 
Movies change my position on social economic or political issues           NaN
When watching movies things get so intense that I have to stop watching    NaN
Gender identity (1 = female; 2 = male; 3 = self-described)                 NaN
Are you an only child? (1: Yes; 0: No; -1: Did not respond)               -1.0
Movies are best enjoyed alone (1: Yes; 0: No; -1: Did not respond)        -1.0
Name: 896, Length: 477, dtype: float64
The Life of David Gale (2003)                                              NaN
Wing Commande

In [2]:
res_abs = np.abs(res)
dict = {}
for i in range(1097):
    val = np.max(res_abs[i])
    index = np.argmax(res_abs[i])
    print("The most correlated value with user %d is %f and it's achieved with user %d "  %(i, val,index))
    dict[val] = [i,index]

The most correlated value with user 0 is 0.534906 and it's achieved with user 583 
The most correlated value with user 1 is 0.706082 and it's achieved with user 831 
The most correlated value with user 2 is 0.782459 and it's achieved with user 896 
The most correlated value with user 3 is 0.631375 and it's achieved with user 896 
The most correlated value with user 4 is 0.524576 and it's achieved with user 896 
The most correlated value with user 5 is 0.588718 and it's achieved with user 99 
The most correlated value with user 6 is 0.578586 and it's achieved with user 239 
The most correlated value with user 7 is 0.466394 and it's achieved with user 850 
The most correlated value with user 8 is 0.706041 and it's achieved with user 896 
The most correlated value with user 9 is 0.739872 and it's achieved with user 1004 
The most correlated value with user 10 is 0.677752 and it's achieved with user 831 
The most correlated value with user 11 is 0.699421 and it's achieved with user 896 
Th

In [6]:
print(data.iloc[896])
print(data.iloc[831])

The Life of David Gale (2003)                                              2.151316
Wing Commander (1999)                                                      2.021127
Django Unchained (2012)                                                    3.153422
Alien (1979)                                                               2.707612
Indiana Jones and the Last Crusade (1989)                                  2.778618
                                                                             ...   
Movies change my position on social economic or political issues           3.319406
When watching movies things get so intense that I have to stop watching    2.159407
Gender identity (1 = female; 2 = male; 3 = self-described)                 1.253495
Are you an only child? (1: Yes; 0: No; -1: Did not respond)               -1.000000
Movies are best enjoyed alone (1: Yes; 0: No; -1: Did not respond)        -1.000000
Name: 896, Length: 477, dtype: float64
The Life of David Gale (2003)        

In [3]:
max_val = max(dict.keys())
print(max_val)
print(dict[max_val])

0.9994072106611809
[896, 831]


### Q2:

We want to find a model between the ratings and the personal part of the data. To do so, consider:


**Part 1**: the ratings of all users over columns 1-400: 

-- Columns 1-400: These columns contain the ratings for the 400 movies (0 to 4, and missing);

call this part `df_rate`


and 


**Part 2**:  the part of the data which includes all users over columns 401-474

-- Columns 401-421: These columns contain self-assessments on sensation seeking behaviors (1-5)

-- Columns 422-464: These columns contain responses to personality questions (1-5)

-- Columns 465-474: These columns contain self-reported movie experience ratings (1-5)

call this part `df_pers`.

---

Our main task is to model: 


`df_pers = function(df_rate)`


---

**Note:** Split the original data into training and testing as the ratio 0.80: 0.20. 


2.1. Model `df_pers = function(df_rate)` by using the linear regression. 

What are the errors on: (i) the training part; (ii) the testing part?




2.2. Model `df_pers = function(df_rate)` by using the ridge regression with hyperparamter values alpha from [0.0, 1e-8, 1e-5, 0.1, 1, 10]. 

For every of the previous values for alpha, what are the errors on: (i) the training part; (ii) the testing part?

What is a best choice for alpha?



2.3. Model `df_pers = function(df_rate)` by using the lasso regression with hyperparamter values alpha from [1e-3, 1e-2, 1e-1, 1]. 

For every of the previous values for alpha, what are the errors on: (i) the training part; (ii) the testing part?

What is a best choice for alpha?


**Note**: Ignore any `convergence warning` in case you may obtain in the Lasso regression.

In [55]:
import sklearn as sk
#data = pd.read_csv("movieReplicationSet.csv")
#data = data.fillna(-1)
buf = data.iloc[:,0:474]
buf = buf.sample(frac = 1)
print(buf)
buf_feature = buf.iloc[:,:400].to_numpy()
buf_target = buf.iloc[:,400:].to_numpy()
print(buf_target.shape)
print(buf_feature.shape)

     The Life of David Gale (2003)  Wing Commander (1999)  \
843                       2.151316               2.021127   
102                       1.000000               2.000000   
470                       2.151316               2.021127   
510                       2.151316               2.021127   
597                       1.000000               1.000000   
..                             ...                    ...   
688                       2.151316               2.021127   
821                       2.151316               2.021127   
212                       2.151316               2.021127   
698                       2.151316               2.021127   
379                       2.151316               2.021127   

     Django Unchained (2012)  Alien (1979)  \
843                 3.153422      2.707612   
102                 2.000000      2.000000   
470                 3.500000      2.707612   
510                 3.153422      2.707612   
597                 3.153422      3.0

In [56]:
thres = int(0.8*len(buf_target))
buf_target_train = buf_target[:thres]
buf_target_valid = buf_target[thres:]
buf_feature_train = buf_feature[:thres]
buf_feature_valid = buf_feature[thres:]
print(buf_target_train.shape)
print(buf_target_valid.shape)

(877, 74)
(220, 74)


In [57]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(buf_feature_train, buf_target_train)
print(reg.score(buf_feature_train, buf_target_train))
print(reg.score(buf_feature_valid, buf_target_valid))

0.5011456451695353
-1.507650061413246


In [41]:
print(buf_feature_train)
print(buf_target_train)
print(buf_feature_valid)
print(buf_target_valid)

[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1.  2. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [ 0.  0. -1. ...  1.  3.  1.]]
[[3. 2. 1. ... 5. 4. 1.]
 [5. 5. 2. ... 4. 1. 2.]
 [2. 5. 1. ... 4. 5. 2.]
 ...
 [4. 5. 2. ... 4. 3. 1.]
 [5. 5. 1. ... 5. 5. 5.]
 [5. 5. 2. ... 1. 1. 1.]]
[[-1.  -1.   3.  ... -1.  -1.  -1. ]
 [ 0.5 -1.   0.  ... -1.  -1.  -1. ]
 [-1.  -1.  -1.  ...  3.  -1.  -1. ]
 ...
 [-1.  -1.   0.  ... -1.  -1.  -1. ]
 [-1.  -1.   3.  ... -1.  -1.  -1. ]
 [-1.  -1.  -1.  ... -1.  -1.  -1. ]]
[[3. 5. 2. ... 4. 4. 2.]
 [4. 4. 2. ... 3. 4. 4.]
 [5. 5. 2. ... 4. 3. 1.]
 ...
 [4. 5. 2. ... 3. 3. 1.]
 [1. 2. 1. ... 4. 4. 4.]
 [2. 4. 1. ... 4. 2. 2.]]


In [42]:
from sklearn import linear_model
for i in [1,0.1,0.01,0.001]:
    las = linear_model.Lasso(alpha=i)
    las.fit(buf_feature_train, buf_target_train)
    print(i)
    print(las.score(buf_feature_train, buf_target_train))
    print(las.score(buf_feature_valid, buf_target_valid))


1
0.003206725719394883
-0.0007549944778300051
0.1
0.1330626012154922
0.03481070774809607
0.01
0.4490311293346574
-0.2634281250429008


c:\users\tonyyyyy\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.5504305230710997, tolerance: 0.1333733181299886
  model = cd_fast.enet_coordinate_descent(
c:\users\tonyyyyy\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1.0580490886337657, tolerance: 0.1971760547320413
  model = cd_fast.enet_coordinate_descent(
c:\users\tonyyyyy\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.06190631917883138, tolerance: 0.05874732041049023
  model = cd_fast.enet_coordinate_descent(
c:\users\tonyyyyy

0.001
0.5185069612576206
-0.8146619180995136


In [58]:
from sklearn.linear_model import Ridge
for i in [0.0, 1e-8, 1e-5, 0.1, 1, 10]:
    rid = Ridge(alpha=i)
    rid.fit(buf_feature_train, buf_target_train)
    print(i)
    print(rid.score(buf_feature_train, buf_target_train))
    print(rid.score(buf_feature_valid, buf_target_valid))

0.0
0.5011456451695352
-1.5076500614132449
1e-08
0.5011456451695353
-1.5076500548074727
1e-05
0.5011456451685865
-1.5076434556914629
0.1
0.501061924471646
-1.44621322879618
1
0.4971766292271097
-1.1142906136362052
10
0.45571250606293323
-0.4827079268683609
